vich_uploader:
    db_driver: orm

    mappings:
       logo_file:
           uri_prefix: '%app.path.logo_file%'
           upload_destination: '%kernel.project_dir%/public%app.path.logo_file%'
           delete_on_update: true
           delete_on_remove: true
           inject_on_load: false
           namer:
                service: Vich\UploaderBundle\Naming\UniqidNamer
         
       ebook_file:
           uri_prefix: '%app.path.ebook_file%'
           upload_destination: '%kernel.project_dir%/public%app.path.ebook_file%'
           delete_on_update: true
           delete_on_remove: true
           inject_on_load: false
           namer:
                service: Vich\UploaderBundle\Naming\UniqidNamer
        
       ebook_illustration:
           uri_prefix: '%app.path.ebook_illustration%'
           upload_destination: '%kernel.project_dir%/public%app.path.ebook_illustration%'
           delete_on_update: true
           delete_on_remove: true
           inject_on_load: false
           namer:
                service: Vich\UploaderBundle\Naming\UniqidNamer

       banner_file:
           uri_prefix: '%app.path.banner_file%'
           upload_destination: '%kernel.project_dir%/public%app.path.banner_file%'
           delete_on_update: true
           delete_on_remove: true
           inject_on_load: false
           namer:
                service: Vich\UploaderBundle\Naming\UniqidNamer

       profile_picture_file:
           uri_prefix: '%app.path.profile_picture_file%'
           upload_destination: '%kernel.project_dir%/public%app.path.profile_picture_file%'
           delete_on_update: true
           delete_on_remove: true
           inject_on_load: false
           namer:
                service: Vich\UploaderBundle\Naming\UniqidNamer
